spring:
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.mongo.MongoAutoConfiguration,
      org.springframework.boot.autoconfigure.data.mongo.MongoDataAutoConfiguration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    data-username: ${SPRING_DATASOURCE_USERNAME}
    data-password: ${SPRING_DATASOURCE_PASSWORD}
  data:
    mongodb:
      repositories:
        type: none