spring:
  application:
    name: coffe-machine-backend
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    data-username: ${SPRING_DATASOURCE_USERNAME}
    data-password: ${SPRING_DATASOURCE_PASSWORD}
